---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/tiporecursos":
    get:
      summary: Lista de Tipos de Recursos
      tags:
      - Tipo Recurso
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/tiporecurso"
            text/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/tiporecurso"
            text/plain:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/tiporecurso"
        '500':
          description: Error interno del servidor
  "/tiporecursos/{id}":
    get:
      summary: Obtener el Tipo de Recurso por id
      tags:
      - Tipo Recurso
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/tiporecurso"
            text/json:
              schema:
                "$ref": "#/components/schemas/tiporecurso"
            text/plain:
              schema:
                "$ref": "#/components/schemas/tiporecurso"
        '404':
          description: Recurso no encontrado
  "/usuarios":
    post:
      summary: Crear usuario
      tags:
      - Usuarios
      parameters: []
      responses:
        '201':
          description: Uusario creado
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/usuario"
            text/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/usuario"
            text/plain:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/usuario"
        '500':
          description: Error interno del servidor
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/usuario"
    get:
      summary: Lista de usuarios
      tags:
      - Usuarios
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/usuario"
            text/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/usuario"
            text/plain:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/usuario"
        '500':
          description: Error interno del servidor
  "/usuarios/{id}":
    get:
      summary: Obtener usuario por id
      tags:
      - Usuarios
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/usuario"
            text/json:
              schema:
                "$ref": "#/components/schemas/usuario"
            text/plain:
              schema:
                "$ref": "#/components/schemas/usuario"
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
    put:
      summary: Actualizar usuario por id
      tags:
      - Usuarios
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/usuario"
            text/json:
              schema:
                "$ref": "#/components/schemas/usuario"
            text/plain:
              schema:
                "$ref": "#/components/schemas/usuario"
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/usuario"
    patch:
      summary: Actualizar usuario por id
      tags:
      - Usuarios
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/usuario"
            text/json:
              schema:
                "$ref": "#/components/schemas/usuario"
            text/plain:
              schema:
                "$ref": "#/components/schemas/usuario"
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/usuario"
    delete:
      summary: Eliminar usuario por id
      tags:
      - Usuarios
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Usuario eliminado
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
components:
  schemas:
    usuario:
      type: object
      properties:
        ID_USUARIO:
          type: integer
        ID_EMPLEADO:
          type: integer
        ID_F_TIPO_USUARIO:
          type: integer
        ID_F_PROFESOR:
          type: integer
        NOMBRE_USUARIO:
          type: string
        CORREO_ELECTRONICO_USUARIO:
          type: string
        DESCRIPCION_ROL:
          type: string
        CONTRASENIA:
          type: string
        ACTIVO_USUARIO:
          type: boolean
        FECHA_CREACION_USUARIO:
          type: string
        FECHA_MODIFICACION_USUARIO:
          type: string
      required:
      - ID_F_TIPO_USUARIO
      - NOMBRE_USUARIO
      - CONTRASENIA
      - ACTIVO_USUARIO
      - FECHA_CREACION_USUARIO
      - FECHA_MODIFICACION_USUARIO
    tiporecurso:
      type: object
      properties:
        ID_TIPO_RECURSO:
          type: integer
        TIPO_RECURSO:
          type: string
      required:
      - ID_TIPO_RECURSO
      - TIPO_RECURSO
    recurso:
      type: object
      properties:
        ID_RECURSO:
          type: integer
        ID_F_RECURSO_PADRE:
          type: integer
        ID_F_TIPO_RECURSO:
          type: integer
        NOMBRE_RECURSO:
          type: string
        RUTA_RECURSO:
          type: string
        DESCRIPCION_RECURSO:
          type: string
        ACTIVO_RECURSO:
          type: boolean
        FECHA_CREACION:
          type: string
        FECHA_MODIFICACION:
          type: string
      required:
      - ID_F_TIPO_RECURSO
      - NOMBRE_RECURSO
      - RUTA_RECURSO
      - ACTIVO_RECURSO
      - FECHA_CREACION
      - FECHA_MODIFICACION
