paises = [
  { ID_PAIS: 1, PAIS: "Afganistán" },
  { ID_PAIS: 2, PAIS: "Albania" },
  { ID_PAIS: 3, PAIS: "Argelia" },
  { ID_PAIS: 4, PAIS: "Andorra" },
  { ID_PAIS: 5, PAIS: "Angola" },
  { ID_PAIS: 6, PAIS: "Antigua y Barbuda" },
  { ID_PAIS: 7, PAIS: "Argentina" },
  { ID_PAIS: 8, PAIS: "Armenia" },
  { ID_PAIS: 9, PAIS: "Australia" },
  { ID_PAIS: 10, PAIS: "Austria" },
  { ID_PAIS: 11, PAIS: "Azerbaiyán" },
  { ID_PAIS: 12, PAIS: "Bahamas" },
  { ID_PAIS: 13, PAIS: "Baréin" },
  { ID_PAIS: 14, PAIS: "Bangladesh" },
  { ID_PAIS: 15, PAIS: "Barbados" },
  { ID_PAIS: 16, PAIS: "Bielorrusia" },
  { ID_PAIS: 17, PAIS: "Bélgica" },
  { ID_PAIS: 18, PAIS: "Belice" },
  { ID_PAIS: 19, PAIS: "Benín" },
  { ID_PAIS: 20, PAIS: "Bután" },
  { ID_PAIS: 21, PAIS: "Bolivia" },
  { ID_PAIS: 22, PAIS: "Bosnia y Herzegovina" },
  { ID_PAIS: 23, PAIS: "Botsuana" },
  { ID_PAIS: 24, PAIS: "Brasil" },
  { ID_PAIS: 25, PAIS: "Brunéi" },
  { ID_PAIS: 26, PAIS: "Bulgaria" },
  { ID_PAIS: 27, PAIS: "Burkina Faso" },
  { ID_PAIS: 28, PAIS: "Burundi" },
  { ID_PAIS: 29, PAIS: "Camboya" },
  { ID_PAIS: 30, PAIS: "Camerún" },
  { ID_PAIS: 31, PAIS: "Canadá" },
  { ID_PAIS: 32, PAIS: "Cabo Verde" },
  { ID_PAIS: 33, PAIS: "República Centroafricana" },
  { ID_PAIS: 34, PAIS: "Chad" },
  { ID_PAIS: 35, PAIS: "Chile" },
  { ID_PAIS: 36, PAIS: "China" },
  { ID_PAIS: 37, PAIS: "Colombia" },
  { ID_PAIS: 38, PAIS: "Comoras" },
  { ID_PAIS: 39, PAIS: "Congo" },
  { ID_PAIS: 40, PAIS: "Costa Rica" },
  { ID_PAIS: 41, PAIS: "Costa de Marfil" },
  { ID_PAIS: 42, PAIS: "Croacia" },
  { ID_PAIS: 43, PAIS: "Cuba" },
  { ID_PAIS: 44, PAIS: "Chipre" },
  { ID_PAIS: 45, PAIS: "República Checa" },
  { ID_PAIS: 46, PAIS: "Dinamarca" },
  { ID_PAIS: 47, PAIS: "Yibuti" },
  { ID_PAIS: 48, PAIS: "Dominica" },
  { ID_PAIS: 49, PAIS: "República Dominicana" },
  { ID_PAIS: 50, PAIS: "Timor Oriental" },
  { ID_PAIS: 51, PAIS: "Ecuador" },
  { ID_PAIS: 52, PAIS: "Egipto" },
  { ID_PAIS: 53, PAIS: "El Salvador" },
  { ID_PAIS: 54, PAIS: "Guinea Ecuatorial" },
  { ID_PAIS: 55, PAIS: "Eritrea" },
  { ID_PAIS: 56, PAIS: "Estonia" },
  { ID_PAIS: 57, PAIS: "Eswatini" },
  { ID_PAIS: 58, PAIS: "Etiopía" },
  { ID_PAIS: 59, PAIS: "Fiyi" },
  { ID_PAIS: 60, PAIS: "Finlandia" },
  { ID_PAIS: 61, PAIS: "Francia" },
  { ID_PAIS: 62, PAIS: "Gabón" },
  { ID_PAIS: 63, PAIS: "Gambia" },
  { ID_PAIS: 64, PAIS: "Georgia" },
  { ID_PAIS: 65, PAIS: "Alemania" },
  { ID_PAIS: 66, PAIS: "Ghana" },
  { ID_PAIS: 67, PAIS: "Grecia" },
  { ID_PAIS: 68, PAIS: "Granada" },
  { ID_PAIS: 69, PAIS: "Guatemala" },
  { ID_PAIS: 70, PAIS: "Guinea" },
  { ID_PAIS: 71, PAIS: "Guinea-Bisáu" },
  { ID_PAIS: 72, PAIS: "Guyana" },
  { ID_PAIS: 73, PAIS: "Haití" },
  { ID_PAIS: 74, PAIS: "Honduras" },
  { ID_PAIS: 75, PAIS: "Hungría" },
  { ID_PAIS: 76, PAIS: "Islandia" },
  { ID_PAIS: 77, PAIS: "India" },
  { ID_PAIS: 78, PAIS: "Indonesia" },
  { ID_PAIS: 79, PAIS: "Irán" },
  { ID_PAIS: 80, PAIS: "Iraq" },
  { ID_PAIS: 81, PAIS: "Irlanda" },
  { ID_PAIS: 82, PAIS: "Israel" },
  { ID_PAIS: 83, PAIS: "Italia" },
  { ID_PAIS: 84, PAIS: "Jamaica" },
  { ID_PAIS: 85, PAIS: "Japón" },
  { ID_PAIS: 86, PAIS: "Jordania" },
  { ID_PAIS: 87, PAIS: "Kazajistán" },
  { ID_PAIS: 88, PAIS: "Kenia" },
  { ID_PAIS: 89, PAIS: "Kiribati" },
  { ID_PAIS: 90, PAIS: "Kuwait" },
  { ID_PAIS: 91, PAIS: "Kirguistán" },
  { ID_PAIS: 92, PAIS: "Laos" },
  { ID_PAIS: 93, PAIS: "Letonia" },
  { ID_PAIS: 94, PAIS: "Líbano" },
  { ID_PAIS: 95, PAIS: "Lesoto" },
  { ID_PAIS: 96, PAIS: "Liberia" },
  { ID_PAIS: 97, PAIS: "Libia" },
  { ID_PAIS: 98, PAIS: "Liechtenstein" },
  { ID_PAIS: 99, PAIS: "Lituania" },
  { ID_PAIS: 100, PAIS: "Luxemburgo" },
  { ID_PAIS: 101, PAIS: "Madagascar" },
  { ID_PAIS: 102, PAIS: "Malaui" },
  { ID_PAIS: 103, PAIS: "Malasia" },
  { ID_PAIS: 104, PAIS: "Maldivas" },
  { ID_PAIS: 105, PAIS: "Malí" },
  { ID_PAIS: 106, PAIS: "Malta" },
  { ID_PAIS: 107, PAIS: "Islas Marshall" },
  { ID_PAIS: 108, PAIS: "Mauritania" },
  { ID_PAIS: 109, PAIS: "Mauricio" },
  { ID_PAIS: 110, PAIS: "México" },
  { ID_PAIS: 111, PAIS: "Micronesia" },
  { ID_PAIS: 112, PAIS: "Moldavia" },
  { ID_PAIS: 113, PAIS: "Mónaco" },
  { ID_PAIS: 114, PAIS: "Mongolia" },
  { ID_PAIS: 115, PAIS: "Montenegro" },
  { ID_PAIS: 116, PAIS: "Marruecos" },
  { ID_PAIS: 117, PAIS: "Mozambique" },
  { ID_PAIS: 118, PAIS: "Myanmar" },
  { ID_PAIS: 119, PAIS: "Namibia" },
  { ID_PAIS: 120, PAIS: "Nauru" },
  { ID_PAIS: 121, PAIS: "Nepal" },
  { ID_PAIS: 122, PAIS: "Países Bajos" },
  { ID_PAIS: 123, PAIS: "Nueva Zelanda" },
  { ID_PAIS: 124, PAIS: "Nicaragua" },
  { ID_PAIS: 125, PAIS: "Níger" },
  { ID_PAIS: 126, PAIS: "Nigeria" },
  { ID_PAIS: 127, PAIS: "Corea del Norte" },
  { ID_PAIS: 128, PAIS: "Macedonia del Norte" },
  { ID_PAIS: 129, PAIS: "Noruega" },
  { ID_PAIS: 130, PAIS: "Omán" },
  { ID_PAIS: 131, PAIS: "Pakistán" },
  { ID_PAIS: 132, PAIS: "Palau" },
  { ID_PAIS: 133, PAIS: "Panamá" },
  { ID_PAIS: 134, PAIS: "Papúa Nueva Guinea" },
  { ID_PAIS: 135, PAIS: "Paraguay" },
  { ID_PAIS: 136, PAIS: "Perú" },
  { ID_PAIS: 137, PAIS: "Filipinas" },
  { ID_PAIS: 138, PAIS: "Polonia" },
  { ID_PAIS: 139, PAIS: "Portugal" },
  { ID_PAIS: 140, PAIS: "Catar" },
  { ID_PAIS: 141, PAIS: "Rumanía" },
  { ID_PAIS: 142, PAIS: "Rusia" },
  { ID_PAIS: 143, PAIS: "Ruanda" },
  { ID_PAIS: 144, PAIS: "San Cristóbal y Nieves" },
  { ID_PAIS: 145, PAIS: "Santa Lucía" },
  { ID_PAIS: 146, PAIS: "San Vicente y las Granadinas" },
  { ID_PAIS: 147, PAIS: "Samoa" },
  { ID_PAIS: 148, PAIS: "San Marino" },
  { ID_PAIS: 149, PAIS: "Santo Tomé y Príncipe" },
  { ID_PAIS: 150, PAIS: "Arabia Saudita" },
  { ID_PAIS: 151, PAIS: "Senegal" },
  { ID_PAIS: 152, PAIS: "Serbia" },
  { ID_PAIS: 153, PAIS: "Seychelles" },
  { ID_PAIS: 154, PAIS: "Sierra Leona" },
  { ID_PAIS: 155, PAIS: "Singapur" },
  { ID_PAIS: 156, PAIS: "Eslovaquia" },
  { ID_PAIS: 157, PAIS: "Eslovenia" },
  { ID_PAIS: 158, PAIS: "Islas Salomón" },
  { ID_PAIS: 159, PAIS: "Somalia" },
  { ID_PAIS: 160, PAIS: "Sudáfrica" },
  { ID_PAIS: 161, PAIS: "Corea del Sur" },
  { ID_PAIS: 162, PAIS: "Sudán del Sur" },
  { ID_PAIS: 163, PAIS: "España" },
  { ID_PAIS: 164, PAIS: "Sri Lanka" },
  { ID_PAIS: 165, PAIS: "Sudán" },
  { ID_PAIS: 166, PAIS: "Surinam" },
  { ID_PAIS: 167, PAIS: "Suecia" },
  { ID_PAIS: 168, PAIS: "Suiza" },
  { ID_PAIS: 169, PAIS: "Siria" },
  { ID_PAIS: 170, PAIS: "Taiwán" },
  { ID_PAIS: 171, PAIS: "Tayikistán" },
  { ID_PAIS: 172, PAIS: "Tanzania" },
  { ID_PAIS: 173, PAIS: "Tailandia" },
  { ID_PAIS: 174, PAIS: "Togo" },
  { ID_PAIS: 175, PAIS: "Tonga" },
  { ID_PAIS: 176, PAIS: "Trinidad y Tobago" },
  { ID_PAIS: 177, PAIS: "Túnez" },
  { ID_PAIS: 178, PAIS: "Turquía" },
  { ID_PAIS: 179, PAIS: "Turkmenistán" },
  { ID_PAIS: 180, PAIS: "Tuvalu" },
  { ID_PAIS: 181, PAIS: "Uganda" },
  { ID_PAIS: 182, PAIS: "Ucrania" },
  { ID_PAIS: 183, PAIS: "Emiratos Árabes Unidos" },
  { ID_PAIS: 184, PAIS: "Reino Unido" },
  { ID_PAIS: 185, PAIS: "Estados Unidos" },
  { ID_PAIS: 186, PAIS: "Uruguay" },
  { ID_PAIS: 187, PAIS: "Uzbekistán" },
  { ID_PAIS: 188, PAIS: "Vanuatu" },
  { ID_PAIS: 189, PAIS: "Ciudad del Vaticano" },
  { ID_PAIS: 190, PAIS: "Venezuela" },
  { ID_PAIS: 191, PAIS: "Vietnam" },
  { ID_PAIS: 192, PAIS: "Yemen" },
  { ID_PAIS: 193, PAIS: "Zambia" },
  { ID_PAIS: 194, PAIS: "Zimbabue" }
]

Pais.upsert_all(paises)
