EstadoObservacionMaestria.upsert_all([
  { ID_ESTADO_OBSERVACION_MAESTRIA: 1, ESTADO_OBSERVACION_MAESTRIA: "Pendiente" },
  { ID_ESTADO_OBSERVACION_MAESTRIA: 2, ESTADO_OBSERVACION_MAESTRIA: "Resuelta" },
])
